export const keyboardLayout = [
  ['Backquote', { color: 'primary', type: 'symbol' }],
  ['Digit1', { color: 'primary', type: 'symbol' }],
  ['Digit2', { color: 'primary', type: 'symbol' }],
  ['Digit3', { color: 'primary', type: 'symbol' }],
  ['Digit4', { color: 'primary', type: 'symbol' }],
  ['Digit5', { color: 'secondary', type: 'symbol' }],
  ['Digit6', { color: 'secondary', type: 'symbol' }],
  ['Digit7', { color: 'secondary', type: 'symbol' }],
  ['Digit8', { color: 'secondary', type: 'symbol' }],
  ['Digit9', { color: 'secondary', type: 'symbol' }],
  ['Digit0', { color: 'primary', type: 'symbol' }],
  ['Minus', { color: 'primary', type: 'symbol' }],
  ['Equal', { color: 'primary', type: 'symbol' }],
  ['Backspace', { color: 'secondary', type: 'backspace' }],
  ['Delete', { color: 'secondary', type: 'symbol' }],
  ['Tab', { color: 'secondary', type: 'tab' }],
  ['KeyQ', { color: 'primary', type: 'symbol' }],
  ['KeyW', { color: 'primary', type: 'symbol' }],
  ['KeyE', { color: 'primary', type: 'symbol' }],
  ['KeyR', { color: 'primary', type: 'symbol' }],
  ['KeyT', { color: 'primary', type: 'symbol' }],
  ['KeyY', { color: 'primary', type: 'symbol' }],
  ['KeyU', { color: 'primary', type: 'symbol' }],
  ['KeyI', { color: 'primary', type: 'symbol' }],
  ['KeyO', { color: 'primary', type: 'symbol' }],
  ['KeyP', { color: 'primary', type: 'symbol' }],
  ['BracketLeft', { color: 'primary', type: 'symbol' }],
  ['BracketRight', { color: 'primary', type: 'symbol' }],
  ['Backslash', { color: 'secondary', type: 'backslash' }],
  ['Home', { color: 'secondary', type: 'symbol' }],
  ['CapsLock', { color: 'secondary', type: 'capslock' }],
  ['KeyA', { color: 'primary', type: 'symbol' }],
  ['KeyS', { color: 'primary', type: 'symbol' }],
  ['KeyD', { color: 'primary', type: 'symbol' }],
  ['KeyF', { color: 'primary', type: 'symbol' }],
  ['KeyG', { color: 'primary', type: 'symbol' }],
  ['KeyH', { color: 'primary', type: 'symbol' }],
  ['KeyJ', { color: 'primary', type: 'symbol' }],
  ['KeyK', { color: 'primary', type: 'symbol' }],
  ['KeyL', { color: 'primary', type: 'symbol' }],
  ['Semicolon', { color: 'primary', type: 'symbol' }],
  ['Quote', { color: 'primary', type: 'symbol' }],
  ['Enter', { color: 'secondary', type: 'enter' }],
  ['PageUp', { color: 'secondary', type: 'symbol' }],
  ['ShiftLeft', { color: 'secondary', type: 'shift-left' }],
  ['KeyZ', { color: 'primary', type: 'symbol' }],
  ['KeyX', { color: 'primary', type: 'symbol' }],
  ['KeyC', { color: 'primary', type: 'symbol' }],
  ['KeyV', { color: 'primary', type: 'symbol' }],
  ['KeyB', { color: 'primary', type: 'symbol' }],
  ['KeyN', { color: 'primary', type: 'symbol' }],
  ['KeyM', { color: 'primary', type: 'symbol' }],
  ['Comma', { color: 'primary', type: 'symbol' }],
  ['Period', { color: 'primary', type: 'symbol' }],
  ['Slash', { color: 'primary', type: 'symbol' }],
  ['ShiftRight', { color: 'secondary', type: 'shift-right' }],
  ['ArrowUp', { color: 'primary', type: 'symbol' }],
  ['PageDown', { color: 'secondary', type: 'symbol' }],
  ['ControlLeft', { color: 'secondary', type: 'wideKey' }],
  ['MetaLeft', { color: 'secondary', type: 'wideKey' }],
  ['AltLeft', { color: 'secondary', type: 'wideKey' }],
  ['Space', { color: 'primary', type: 'space' }],
  ['AltRight', { color: 'secondary', type: 'wideKey' }],
  ['MetaRight', { color: 'secondary', type: 'wideKey' }],
  ['ControlRight', { color: 'secondary', type: 'wideKey' }],
  ['ArrowLeft', { color: 'primary', type: 'symbol' }],
  ['ArrowDown', { color: 'primary', type: 'symbol' }],
  ['ArrowRight', { color: 'primary', type: 'symbol' }],
];

export const langs = ['ru', 'en'];

export const keysMap = {
  functional: {
    Escape: 'Escape',
    F1: 'F1',
    F2: 'F2',
    F3: 'F3',
    F4: 'F4',
    F5: 'F5',
    F6: 'F6',
    F7: 'F7',
    F8: 'F8',
    F9: 'F9',
    F10: 'F10',
    F11: 'F11',
    F12: 'F12',
    Tab: 'tab',
    CapsLock: 'caps',
    ShiftLeft: 'shift',
    ControlLeft: 'control',
    MetaLeft: 'win',
    AltLeft: 'alt',
    Space: ' ',
    AltRight: 'alt',
    MetaRight: 'win',
    ContextMenu: 'ContextMenu',
    ControlRight: 'control',
    ScrollLock: 'scroll lock',
    Pause: 'pause',
    PageUp: 'page up',
    PageDown: 'page down',
    End: 'end',
    Home: 'home',
    Insert: 'ins',
    Delete: 'del',
    Backspace: '⟵',
    ArrowUp: '˄',
    ArrowLeft: '˂',
    ArrowRight: '˃',
    ArrowDown: '˅',
    NumLock: 'num lock',
  },
  numPad: {
    NumpadDivide: { numLock: '/', main: '/' },
    NumpadMultiply: { numLock: '*', main: '*' },
    NumpadSubtract: { numLock: '-', main: '-' },
    NumpadAdd: { numLock: '+', main: '+' },
    NumpadEnter: { numLock: 'Enter', main: 'Enter' },
    Numpad7: { numLock: '7', main: 'Home' },
    Numpad8: { numLock: '8', main: 'ArrowUp' },
    Numpad9: { numLock: '9', main: 'PageUp' },
    Numpad4: { numLock: '4', main: 'ArrowLeft' },
    Numpad5: { numLock: '5', main: 'Clear' },
    Numpad6: { numLock: '6', main: 'ArrowRight' },
    Numpad1: { numLock: '1', main: 'End' },
    Numpad2: { numLock: '2', main: 'ArrowDown' },
    Numpad3: { numLock: '3', main: 'PageDown' },
    Numpad0: { numLock: '0', main: 'Insert' },
    NumpadDecimal: { numLock: '.', main: 'Delete' },
  },
  symbols: {
    en: {
      Digit1: { shift: '!', main: '1' },
      Digit2: { shift: '@', main: '2' },
      Digit3: { shift: '#', main: '3' },
      Digit4: { shift: '$', main: '4' },
      Digit5: { shift: '%', main: '5' },
      Digit6: { shift: '^', main: '6' },
      Digit7: { shift: '&', main: '7' },
      Digit8: { shift: '*', main: '8' },
      Digit9: { shift: '(', main: '9' },
      Digit0: { shift: ')', main: '0' },
      Minus: { shift: '_', main: '-' },
      Equal: { shift: '+', main: '=' },
      Backslash: { shift: '|', main: '\\' },
      KeyQ: { shift: 'Q', main: 'q' },
      KeyW: { shift: 'W', main: 'w' },
      KeyE: { shift: 'E', main: 'e' },
      KeyR: { shift: 'R', main: 'r' },
      KeyT: { shift: 'T', main: 't' },
      KeyY: { shift: 'Y', main: 'y' },
      KeyU: { shift: 'U', main: 'u' },
      KeyI: { shift: 'I', main: 'i' },
      KeyO: { shift: 'O', main: 'o' },
      KeyP: { shift: 'P', main: 'p' },
      BracketLeft: { shift: '{', main: '[' },
      BracketRight: { shift: '}', main: ']' },
      KeyA: { shift: 'A', main: 'a' },
      KeyS: { shift: 'S', main: 's' },
      KeyD: { shift: 'D', main: 'd' },
      KeyF: { shift: 'F', main: 'f' },
      KeyG: { shift: 'G', main: 'g' },
      KeyH: { shift: 'H', main: 'h' },
      KeyJ: { shift: 'J', main: 'j' },
      KeyK: { shift: 'K', main: 'k' },
      KeyL: { shift: 'L', main: 'l' },
      Semicolon: { shift: ':', main: ';' },
      Quote: { shift: '"', main: "'" },
      KeyZ: { shift: 'Z', main: 'z' },
      KeyX: { shift: 'X', main: 'x' },
      KeyC: { shift: 'C', main: 'c' },
      KeyV: { shift: 'V', main: 'v' },
      KeyB: { shift: 'B', main: 'b' },
      KeyN: { shift: 'N', main: 'n' },
      KeyM: { shift: 'M', main: 'm' },
      Comma: { shift: '<', main: ',' },
      Period: { shift: '>', main: '.' },
      Slash: { shift: '?', main: '/' },
      Backquote: { shift: '~', main: '`' },
    },
    ru: {
      Backquote: { shift: 'Ё', main: 'ё' },
      Digit1: { shift: '!', main: '1' },
      Digit2: { shift: '"', main: '2' },
      Digit3: { shift: '№', main: '3' },
      Digit4: { shift: ';', main: '4' },
      Digit5: { shift: '%', main: '5' },
      Digit6: { shift: ':', main: '6' },
      Digit7: { shift: '?', main: '7' },
      Digit8: { shift: '*', main: '8' },
      Digit9: { shift: '(', main: '9' },
      Digit0: { shift: ')', main: '0' },
      Minus: { shift: '_', main: '-' },
      Equal: { shift: '+', main: '=' },
      Backslash: { shift: '/', main: '\\' },
      KeyQ: { shift: 'Й', main: 'й' },
      KeyW: { shift: 'Ц', main: 'ц' },
      KeyE: { shift: 'У', main: 'у' },
      KeyR: { shift: 'К', main: 'к' },
      KeyT: { shift: 'Е', main: 'е' },
      KeyY: { shift: 'Н', main: 'н' },
      KeyU: { shift: 'Г', main: 'г' },
      KeyI: { shift: 'Ш', main: 'ш' },
      KeyO: { shift: 'Щ', main: 'щ' },
      KeyP: { shift: 'З', main: 'з' },
      BracketLeft: { shift: 'Х', main: 'х' },
      BracketRight: { shift: 'Ъ', main: 'ъ' },
      KeyA: { shift: 'Ф', main: 'ф' },
      KeyS: { shift: 'Ы', main: 'ы' },
      KeyD: { shift: 'В', main: 'в' },
      KeyF: { shift: 'А', main: 'а' },
      KeyG: { shift: 'П', main: 'п' },
      KeyH: { shift: 'Р', main: 'р' },
      KeyJ: { shift: 'О', main: 'о' },
      KeyK: { shift: 'Л', main: 'л' },
      KeyL: { shift: 'Д', main: 'д' },
      Semicolon: { shift: 'Ж', main: 'ж' },
      Quote: { shift: 'Э', main: 'э' },
      KeyZ: { shift: 'Я', main: 'я' },
      KeyX: { shift: 'Ч', main: 'ч' },
      KeyC: { shift: 'С', main: 'с' },
      KeyV: { shift: 'М', main: 'м' },
      KeyB: { shift: 'И', main: 'и' },
      KeyN: { shift: 'Т', main: 'т' },
      KeyM: { shift: 'Ь', main: 'ь' },
      Comma: { shift: 'Б', main: 'б' },
      Period: { shift: 'Ю', main: 'ю' },
      Slash: { shift: ',', main: '.' },
    },
  },
};
